import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { rawAssets } from '../../packages/assets/src/catalog.js';
import { resolveAssetCatalog } from '../../packages/assets/src/resolver.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const repositoryRoot = path.resolve(projectRoot, '..');

const sourceExamplesDir = path.resolve(repositoryRoot, 'examples');
const sourceAssetsDir = path.resolve(sourceExamplesDir, 'assets');
const sourceCatalogDemoDir = path.resolve(repositoryRoot, 'packages', 'assets', 'demo');
const sourceCatalogTechnicalDir = path.resolve(repositoryRoot, 'packages', 'assets', 'technical');

const targetExamplesDir = path.resolve(projectRoot, 'public', 'examples');
const targetAssetsDir = path.resolve(projectRoot, 'public', 'assets');
const targetCatalogDemoDir = path.resolve(targetAssetsDir, 'demo');
const targetCatalogTechnicalDir = path.resolve(targetAssetsDir, 'technical');

const ensureSource = (dirPath: string): void => {
    if (!fs.existsSync(dirPath)) {
        throw new Error(`[examples:sync] Missing source directory: ${dirPath}`);
    }
};

const resetDir = (dirPath: string): void => {
    fs.rmSync(dirPath, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(dirPath), { recursive: true });
};

const copyRecursive = (sourceDir: string, targetDir: string): void => {
    fs.cpSync(sourceDir, targetDir, { recursive: true, force: true });
};

const run = (): void => {
    ensureSource(sourceExamplesDir);
    ensureSource(sourceAssetsDir);
    ensureSource(sourceCatalogDemoDir);
    ensureSource(sourceCatalogTechnicalDir);

    resetDir(targetExamplesDir);
    resetDir(targetAssetsDir);

    copyRecursive(sourceExamplesDir, targetExamplesDir);
    copyRecursive(sourceAssetsDir, targetAssetsDir);
    copyRecursive(sourceCatalogDemoDir, targetCatalogDemoDir);
    copyRecursive(sourceCatalogTechnicalDir, targetCatalogTechnicalDir);

    // Keep runtime serving deterministic: examples/assets is canonical source,
    // but the playground runtime expects /assets/* URLs.
    fs.rmSync(path.resolve(targetExamplesDir, 'assets'), { recursive: true, force: true });

    // Generate assets/catalog.js — the @assets import-map module consumed by
    // example scripts. Paths are resolved relative to preview.html (i.e.
    // 'assets/demo/…', 'assets/technical/…') so no basePath is needed in loaders.
    const resolved = resolveAssetCatalog(rawAssets, 'assets/');
    const catalogLines = [
        '// Auto-generated by examples:sync — do not edit.',
        '',
        ...Object.entries(resolved).map(
            ([key, value]) => `export const ${key} = ${JSON.stringify(value, null, 4)};`,
        ),
        '',
    ];
    fs.writeFileSync(path.resolve(targetAssetsDir, 'catalog.js'), catalogLines.join('\n'), 'utf8');

    console.log(`[examples:sync] Copied ${sourceExamplesDir} -> ${targetExamplesDir}`);
    console.log(`[examples:sync] Copied ${sourceAssetsDir} -> ${targetAssetsDir}`);
    console.log(`[examples:sync] Copied ${sourceCatalogDemoDir} -> ${targetCatalogDemoDir}`);
    console.log(`[examples:sync] Copied ${sourceCatalogTechnicalDir} -> ${targetCatalogTechnicalDir}`);
    console.log(`[examples:sync] Generated ${path.resolve(targetAssetsDir, 'catalog.js')}`);
};

run();
