import { Application, Asset, Color, Container, Keyboard, type PixelSnapMode, Rectangle, type RenderingContext, Scene, Sprite, Spritesheet, type SpritesheetData, TextureRegion, type Time, View } from '@codexo/exojs';
import { TILE_TRANSFORM_IDENTITY, TileLayer, TileMap, tilemapExtension, TileSet, type TileMapView } from '@codexo/exojs-tilemap';
import { mountControlPanel, mountControls } from '@examples/runtime';

// Core @codexo/exojs-tilemap API, with no on-disk map format involved: a
// procedural TileMap built entirely from code.
//
//   - Chunked rendering: the map is much bigger than the viewport (48x32
//     tiles == 3072x2048px). TileLayer stores tiles in 16x16-tile chunks;
//     TileLayerNode renders one instanced draw call per non-empty *visible*
//     chunk, culling the rest by their local bounds every frame — nothing in
//     this example does that culling manually.
//   - TileMapView + bands: `map.createView({ bands })` groups the map's
//     layers into named TileMapBands. Placing `actorLayer` between the
//     'ground' and 'canopy' bands makes the explorer sprite render under the
//     canopy tiles and over the ground tiles, without either layer knowing
//     the actor exists.
//   - PixelSnapMode: cycle through 'none' / 'position' / 'geometry' on the
//     view — it cascades to every TileLayerNode and chunk (see the "Pixel
//     snapping" guide for what each mode does).

const TILE = 64;
const COLUMNS = 48;
const ROWS = 32;
const MAP_WIDTH = COLUMNS * TILE;
const MAP_HEIGHT = ROWS * TILE;
const MOVE_SPEED = 260;

const app = new Application({
    canvas: {
        width: 1280,
        height: 720,
        mount: document.body,
        sizingMode: 'fit',
    },
    clearColor: new Color(20, 28, 22),
    // The tilemap extension wires the per-backend chunk renderer so
    // TileLayerNode (generated by TileMapView) can draw.
    extensions: [tilemapExtension],
    // No loader.basePath here: every asset below comes from the shared
    // `assets` catalog, whose URLs are already fully resolved.
});

class TileChunksAndBandsScene extends Scene {
    private camera!: View;
    private explorer!: Sprite;
    private worldRoot!: Container;
    private mapView!: TileMapView;
    private moveX = 0;
    private moveY = 0;
    private hud!: ReturnType<typeof mountControls>;

    override async init(): Promise<void> {
        // ── Tileset + two layers, built entirely in code ──────────────────
        // Await the atlas load: TileSet needs a TextureRegion with real
        // dimensions, so a not-yet-hydrated `loader.get()` handle is not enough.
        const tilesTexture = await this.loader.load(Asset.kind('texture', assets.demo.tilesets.map.image));
        const tileset = new TileSet({
            name: 'map',
            texture: new TextureRegion(tilesTexture, { x: 0, y: 0, width: tilesTexture.width, height: tilesTexture.height }),
            tileWidth: TILE,
            tileHeight: TILE,
            tileCount: 204,
            columns: 17,
        });

        // 16x16-tile chunks (smaller than the 32x32 default) so a 48x32 map
        // spans a visible 3x2 chunk grid per layer — six TileChunkNodes each.
        const ground = new TileLayer({ id: 1, name: 'ground', width: COLUMNS, height: ROWS, tileWidth: TILE, tileHeight: TILE, tilesets: [tileset], chunkWidth: 16, chunkHeight: 16 });
        const canopy = new TileLayer({ id: 2, name: 'canopy', width: COLUMNS, height: ROWS, tileWidth: TILE, tileHeight: TILE, tilesets: [tileset], chunkWidth: 16, chunkHeight: 16 });

        for (let ty = 0; ty < ROWS; ty++) {
            for (let tx = 0; tx < COLUMNS; tx++) {
                // Deterministic scatter: a "path" tile threaded through the
                // grass, and sparse overhead canopy tiles above it.
                const groundTile = (tx * 3 + ty * 5) % 11 === 0 ? 1 : 0;
                ground.setTileAt(tx, ty, { tileset, localTileId: groundTile, transform: TILE_TRANSFORM_IDENTITY });

                if ((tx * 7 + ty * 3) % 17 === 0) {
                    canopy.setTileAt(tx, ty, { tileset, localTileId: 9, transform: TILE_TRANSFORM_IDENTITY });
                }
            }
        }

        const map = new TileMap({ name: 'explorable-world', width: COLUMNS, height: ROWS, tileWidth: TILE, tileHeight: TILE, tilesets: [tileset], layers: [ground, canopy] });

        // ── TileMapView: group layers into bands, place actors between ────
        this.mapView = map.createView({ bands: { ground: ['ground'], canopy: ['canopy'] } });

        const characters = new Spritesheet(
            this.loader.get(assets.demo.spritesheets.platformerCharacters.image),
            (await this.loader.load(Asset.kind('json', assets.demo.spritesheets.platformerCharacters.data))) as SpritesheetData,
        );

        this.explorer = characters.getFrameSprite('character_green_front').setAnchor(0.5);
        this.explorer.setPosition(MAP_WIDTH / 2, MAP_HEIGHT / 2);
        this.explorer.setScale(1.25);

        const actorLayer = new Container();
        actorLayer.addChild(this.explorer);

        this.worldRoot = new Container();
        // Render order: ground band -> actors -> canopy band. The canopy
        // tiles visually cover the explorer whenever they overlap.
        this.worldRoot.addChild(this.mapView.band('ground'), actorLayer, this.mapView.band('canopy'));

        // ── Camera: follows the explorer, clamped to the map bounds ───────
        const { width, height } = app.canvas;

        this.camera = new View(this.explorer.x, this.explorer.y, width, height);
        this.camera.follow(this.explorer, { lerp: 0.12 });
        this.camera.setBounds(new Rectangle(0, 0, MAP_WIDTH, MAP_HEIGHT));

        this.setupInput();
        this.setupHud();
    }

    private setupInput(): void {
        this.inputs.onActive(Keyboard.A, () => (this.moveX = -1));
        this.inputs.onStop(Keyboard.A, () => {
            if (this.moveX < 0) this.moveX = 0;
        });
        this.inputs.onActive(Keyboard.D, () => (this.moveX = 1));
        this.inputs.onStop(Keyboard.D, () => {
            if (this.moveX > 0) this.moveX = 0;
        });
        this.inputs.onActive(Keyboard.W, () => (this.moveY = -1));
        this.inputs.onStop(Keyboard.W, () => {
            if (this.moveY < 0) this.moveY = 0;
        });
        this.inputs.onActive(Keyboard.S, () => (this.moveY = 1));
        this.inputs.onStop(Keyboard.S, () => {
            if (this.moveY > 0) this.moveY = 0;
        });
    }

    private setupHud(): void {
        const chunkCount = (name: string): number => {
            const layer = this.mapView.getLayerNodesByName(name)[0];
            return layer ? layer.children.length : 0;
        };

        this.hud = mountControls({
            title: 'Tilemap Chunks & Layer Bands',
            controls: [
                { keys: 'WASD', action: 'move the explorer' },
                { keys: 'panel', action: 'toggle canopy band / pixel snapping' },
            ],
            status: `${chunkCount('ground')} ground chunks, ${chunkCount('canopy')} canopy chunks loaded`,
            hint: 'The explorer renders between the ground and canopy TileMapBands — canopy tiles draw over it. Camera culling of off-screen chunks is automatic.',
        });

        const panel = mountControlPanel({ title: 'Tilemap' });
        panel.addToggle({
            label: 'Canopy band',
            value: true,
            onChange: visible => {
                this.mapView.band('canopy').visible = visible;
            },
        });
        panel.addCycle({
            label: 'Pixel snap',
            options: ['none', 'position', 'geometry'],
            index: 0,
            onChange: (_, mode) => {
                this.mapView.pixelSnapMode = mode as PixelSnapMode;
            },
        });
    }

    override update(delta: Time): void {
        if (this.moveX !== 0 || this.moveY !== 0) {
            const length = Math.hypot(this.moveX, this.moveY) || 1;

            this.explorer.move((this.moveX / length) * MOVE_SPEED * delta.seconds, (this.moveY / length) * MOVE_SPEED * delta.seconds);
            this.explorer.x = Math.min(Math.max(this.explorer.x, 0), MAP_WIDTH);
            this.explorer.y = Math.min(Math.max(this.explorer.y, 0), MAP_HEIGHT);
        }
    }

    override draw(context: RenderingContext): void {
        context.backend.clear();
        context.render(this.worldRoot, { view: this.camera });
    }
}

app.start(new TileChunksAndBandsScene());
