// AUTO-GENERATED by `pnpm -C site examples:sync` — DO NOT EDIT BY HAND.
// Source of truth: examples/assets/assets.ts (the canonical hierarchical catalog).
// Regenerate with `tsx scripts/generate-examples-global-dts.ts`; drift is guarded
// by test/examples/assets-global-dts.test.ts.
//
// Self-contained, importless typing for the globally-injected `assets` catalog.
// The value is installed on `globalThis`/`window` by the controlled example
// runtimes (Playground iframe, Example/Guide preview, Asset Browser, smoke
// harness, Full Release harness) BEFORE the example module evaluates. Example
// authors use it directly with full autocomplete and exact literal types — no
// import:
//
//   assets.demo.textures.particleFlame;
//   assets.demo.audio.musicLoop;
//   assets.technical.alpha.alphaEdgeStraight;
//
// It is NOT part of the engine public API and is unavailable in consumer apps.

type ExampleAssetCatalog = {
    readonly demo: {
        readonly textures: {
            readonly particleFlame: 'demo/textures/particle-flame.png';
            readonly particleSmoke: 'demo/textures/particle-smoke.png';
            readonly particleStar: 'demo/textures/particle-star.png';
            readonly particleSpark: 'demo/textures/particle-spark.png';
            readonly particleLight: 'demo/textures/particle-light.png';
            readonly shipA: 'demo/textures/ship-a.png';
            readonly pixelWhite: 'demo/textures/pixel-white.png';
            readonly pixelBlack: 'demo/textures/pixel-black.png';
            readonly pixelTransparent: 'demo/textures/pixel-transparent.png';
            readonly checkerboardTransparent: 'demo/textures/checkerboard-transparent.png';
            readonly kenneyUv: 'demo/textures/kenney-uv.png';
            readonly prototypeDark01: 'demo/textures/prototype-dark-01.png';
            readonly prototypeLight01: 'demo/textures/prototype-light-01.png';
            readonly prototypeGrid: 'demo/textures/prototype-grid.png';
        };
        readonly sprites: {
            readonly buttons: {
                readonly image: 'demo/sprites/buttons.png';
                readonly data: 'demo/sprites/buttons.json';
            };
        };
        readonly spritesheets: {
            readonly buttons: {
                readonly image: 'demo/sprites/buttons.png';
                readonly data: 'demo/sprites/buttons.json';
            };
            readonly platformerBackgrounds: {
                readonly image: 'demo/spritesheets/kenney/platformer-backgrounds.png';
                readonly data: 'demo/spritesheets/kenney/platformer-backgrounds.json';
            };
            readonly platformerCharacters: {
                readonly image: 'demo/spritesheets/kenney/platformer-characters.png';
                readonly data: 'demo/spritesheets/kenney/platformer-characters.json';
            };
            readonly platformerEnemies: {
                readonly image: 'demo/spritesheets/kenney/platformer-enemies.png';
                readonly data: 'demo/spritesheets/kenney/platformer-enemies.json';
            };
            readonly platformerTiles: {
                readonly image: 'demo/spritesheets/kenney/platformer-tiles.png';
                readonly data: 'demo/spritesheets/kenney/platformer-tiles.json';
            };
            readonly backgroundElements: {
                readonly image: 'demo/spritesheets/kenney/background-elements.png';
                readonly data: 'demo/spritesheets/kenney/background-elements.json';
            };
            readonly mapPack: {
                readonly image: 'demo/spritesheets/kenney/map-pack.png';
                readonly data: 'demo/spritesheets/kenney/map-pack.json';
            };
        };
        readonly tilesets: {
            readonly platformer: {
                readonly image: 'demo/spritesheets/kenney/platformer-tiles.png';
                readonly data: 'demo/spritesheets/kenney/platformer-tiles.json';
                readonly tileWidth: 64;
                readonly tileHeight: 64;
            };
            readonly map: {
                readonly image: 'demo/vendor/kenney/map-pack/Tilesheet/mapPack_tilesheet.png';
                readonly tileWidth: 64;
                readonly tileHeight: 64;
            };
        };
        readonly audio: {
            readonly uiClick: 'demo/audio/ui-click.ogg';
            readonly uiConfirm: 'demo/audio/ui-confirm.ogg';
            readonly uiBong: 'demo/audio/ui-bong.ogg';
            readonly impactLight: 'demo/audio/impact-light.ogg';
            readonly impactHeavy: 'demo/audio/impact-heavy.ogg';
            readonly musicA: 'demo/audio/demo-loop-a.ogg';
            readonly musicB: 'demo/audio/demo-loop-b.ogg';
            readonly musicLoop: 'demo/audio/demo-loop-main.ogg';
        };
        readonly sound: {
            readonly uiClick: 'demo/sound/ui-click.ogg';
            readonly uiConfirm: 'demo/sound/ui-confirm.ogg';
            readonly uiBong: 'demo/sound/ui-bong.ogg';
            readonly back: 'demo/sound/back.ogg';
            readonly clickAlt: 'demo/sound/click-alt.ogg';
            readonly switch: 'demo/sound/switch.ogg';
            readonly impactLight: 'demo/sound/impact-light.ogg';
            readonly impactHeavy: 'demo/sound/impact-heavy.ogg';
            readonly impactWood: 'demo/sound/impact-wood.ogg';
            readonly jump: 'demo/sound/jump.ogg';
            readonly coin: 'demo/sound/coin.ogg';
            readonly hurt: 'demo/sound/hurt.ogg';
            readonly powerUp: 'demo/sound/power-up.ogg';
            readonly laser: 'demo/sound/laser.ogg';
        };
        readonly music: {
            readonly loopA: 'demo/music/demo-loop-a.ogg';
            readonly loopB: 'demo/music/demo-loop-b.ogg';
            readonly loopMain: 'demo/music/demo-loop-main.ogg';
            readonly jingleSuccess: 'demo/music/jingle-success.ogg';
            readonly jingleFailure: 'demo/music/jingle-failure.ogg';
            readonly jingleRetroA: 'demo/music/jingle-retro-a.ogg';
            readonly jingleRetroB: 'demo/music/jingle-retro-b.ogg';
        };
        readonly soundSprites: {
            readonly ui: {
                readonly audio: 'demo/sound-sprites/ui/ui.ogg';
                readonly data: 'demo/sound-sprites/ui/ui.json';
            };
            readonly impacts: {
                readonly audio: 'demo/sound-sprites/impacts/impacts.ogg';
                readonly data: 'demo/sound-sprites/impacts/impacts.json';
            };
            readonly digital: {
                readonly audio: 'demo/sound-sprites/digital/digital.ogg';
                readonly data: 'demo/sound-sprites/digital/digital.json';
            };
        };
        readonly fonts: {
            readonly kenneyFuture: 'demo/fonts/Kenney Future.ttf';
            readonly kenneyPixel: 'demo/fonts/Kenney Pixel.ttf';
            readonly kenneyMini: 'demo/fonts/Kenney Mini.ttf';
            readonly kenneyMiniSquareMono: 'demo/fonts/Kenney Mini Square Mono.ttf';
            readonly kenneyBlocksFnt: 'demo/fonts/kenney-blocks-32.fnt';
            readonly kenneyBlocksPng: 'demo/fonts/kenney-blocks-32.png';
        };
        readonly backgrounds: {
            readonly platformerClouds: 'demo/backgrounds/platformer-clouds.png';
            readonly platformerHills: 'demo/backgrounds/platformer-hills.png';
            readonly castles: 'demo/backgrounds/castles.png';
            readonly forest: 'demo/backgrounds/forest.png';
        };
        readonly cursors: {
            readonly arrow: 'demo/cursors/arrow.svg';
            readonly pointer: 'demo/cursors/pointer.svg';
            readonly hand: 'demo/cursors/hand.svg';
            readonly busy: 'demo/cursors/busy.svg';
            readonly cross: 'demo/cursors/cross.svg';
        };
        readonly svg: {
            readonly play: 'demo/svg/play.svg';
            readonly pause: 'demo/svg/pause.svg';
            readonly reset: 'demo/svg/reset.svg';
            readonly arrowRight: 'demo/svg/arrow-right.svg';
            readonly sparkle: 'demo/svg/sparkle.svg';
            readonly audioWave: 'demo/svg/audio-wave.svg';
            readonly imagePlaceholder: 'demo/svg/image-placeholder.svg';
            readonly runeMark: 'demo/svg/rune-mark.svg';
        };
        readonly video: {
            readonly demoLoop: 'demo/video/demo-loop.webm';
            readonly highRes: 'demo/video/high-res.mp4';
            readonly highFps: 'demo/video/high-fps.webm';
            readonly hdr10: 'demo/video/hdr10.webm';
        };
        readonly inputPrompts: {
            readonly generic: {
                readonly image: 'demo/input-prompts/generic.png';
                readonly data: 'demo/input-prompts/generic.json';
            };
            readonly xboxSeries: {
                readonly image: 'demo/input-prompts/xbox-series.png';
                readonly data: 'demo/input-prompts/xbox-series.json';
            };
            readonly playstationSeries: {
                readonly image: 'demo/input-prompts/playstation-series.png';
                readonly data: 'demo/input-prompts/playstation-series.json';
            };
            readonly nintendoSwitch: {
                readonly image: 'demo/input-prompts/nintendo-switch.png';
                readonly data: 'demo/input-prompts/nintendo-switch.json';
            };
            readonly keyboardMouse: {
                readonly image: 'demo/input-prompts/keyboard-mouse.png';
                readonly data: 'demo/input-prompts/keyboard-mouse.json';
            };
        };
        readonly vendor: {
            readonly kenneyManifest: 'demo/vendor/kenney/manifest.json';
        };
    };
    readonly technical: {
        readonly alpha: {
            readonly alphaEdgeStraight: 'technical/alpha/alpha-edge-straight.png';
            readonly alphaGradientRings: 'technical/alpha/alpha-gradient-rings.png';
        };
        readonly filtering: {
            readonly checker256: 'technical/filtering/checker-256.png';
            readonly pixelGrid128: 'technical/filtering/pixel-grid-128.png';
            readonly uvGrid256: 'technical/filtering/uv-grid-256.png';
        };
        readonly color: {
            readonly srgbRamp: 'technical/color/srgb-ramp.png';
            readonly hueRamp: 'technical/color/hue-ramp.png';
            readonly primaryRamp: 'technical/color/primary-ramp.png';
        };
    };
};

declare global {
    const assets: ExampleAssetCatalog;

    interface Window {
        readonly assets: ExampleAssetCatalog;
    }
}

export {};
