// Type declarations for the '@assets' import-map module generated by examples:sync.
// Paths are relative to preview.html — no loader basePath needed.

export declare const textures: {
    readonly particleFlame: string;
    readonly particleSmoke: string;
    readonly particleStar: string;
    readonly particleSpark: string;
    readonly particleLight: string;
    readonly shipA: string;
    readonly pixelWhite: string;
    readonly pixelBlack: string;
    readonly pixelTransparent: string;
    readonly checkerboardTransparent: string;
    readonly kenneyUv: string;
    readonly prototypeDark01: string;
    readonly prototypeLight01: string;
    readonly prototypeGrid: string;
};

export declare const sprites: {
    readonly buttons: { readonly image: string; readonly data: string; };
};

export declare const spritesheets: {
    readonly buttons: { readonly image: string; readonly data: string; };
    readonly platformerBackgrounds: { readonly image: string; readonly data: string; };
    readonly platformerCharacters: { readonly image: string; readonly data: string; };
    readonly platformerEnemies: { readonly image: string; readonly data: string; };
    readonly platformerTiles: { readonly image: string; readonly data: string; };
    readonly backgroundElements: { readonly image: string; readonly data: string; };
    readonly mapPack: { readonly image: string; readonly data: string; };
};

export declare const tilesets: {
    readonly platformer: { readonly image: string; readonly data: string; readonly tileWidth: number; readonly tileHeight: number; };
    readonly map: { readonly image: string; readonly tileWidth: number; readonly tileHeight: number; };
};

export declare const audio: {
    readonly uiClick: string;
    readonly uiConfirm: string;
    readonly uiBong: string;
    readonly impactLight: string;
    readonly impactHeavy: string;
    readonly musicA: string;
    readonly musicB: string;
    readonly musicLoop: string;
};

export declare const sound: {
    readonly uiClick: string;
    readonly uiConfirm: string;
    readonly uiBong: string;
    readonly back: string;
    readonly clickAlt: string;
    readonly switch: string;
    readonly impactLight: string;
    readonly impactHeavy: string;
    readonly impactWood: string;
    readonly jump: string;
    readonly coin: string;
    readonly hurt: string;
    readonly powerUp: string;
    readonly laser: string;
};

export declare const music: {
    readonly loopA: string;
    readonly loopB: string;
    readonly loopMain: string;
    readonly jingleSuccess: string;
    readonly jingleFailure: string;
    readonly jingleRetroA: string;
    readonly jingleRetroB: string;
};

export declare const soundSprites: {
    readonly ui: { readonly audio: string; readonly data: string; };
    readonly impacts: { readonly audio: string; readonly data: string; };
    readonly digital: { readonly audio: string; readonly data: string; };
};

export declare const fonts: {
    readonly kenneyFuture: string;
    readonly kenneyPixel: string;
    readonly kenneyMini: string;
    readonly kenneyMiniSquareMono: string;
};

export declare const backgrounds: {
    readonly platformerClouds: string;
    readonly platformerHills: string;
    readonly castles: string;
    readonly forest: string;
};

export declare const cursors: {
    readonly arrow: string;
    readonly pointer: string;
    readonly hand: string;
    readonly busy: string;
    readonly cross: string;
};

export declare const svg: {
    readonly play: string;
    readonly pause: string;
    readonly reset: string;
    readonly arrowRight: string;
    readonly sparkle: string;
    readonly audioWave: string;
    readonly imagePlaceholder: string;
    readonly runeMark: string;
};

export declare const video: {
    readonly demoLoop: string;
    readonly highRes: string;
    readonly highFps: string;
    readonly hdr10: string;
};

export declare const inputPrompts: {
    readonly generic: { readonly image: string; readonly data: string; };
    readonly xboxSeries: { readonly image: string; readonly data: string; };
    readonly playstationSeries: { readonly image: string; readonly data: string; };
    readonly nintendoSwitch: { readonly image: string; readonly data: string; };
    readonly keyboardMouse: { readonly image: string; readonly data: string; };
};

export declare const technical: {
    readonly alpha: {
        readonly alphaEdgeStraight: string;
        readonly alphaGradientRings: string;
    };
    readonly filtering: {
        readonly checker256: string;
        readonly pixelGrid128: string;
        readonly uvGrid256: string;
    };
    readonly color: {
        readonly srgbRamp: string;
        readonly hueRamp: string;
        readonly primaryRamp: string;
    };
};

export declare const vendor: {
    readonly kenneyManifest: string;
};
