/**
 * Directories a local run leaves behind, and which of them are safe to delete.
 *
 * Everything listed here is gitignored and regenerated by the step that wrote
 * it. Private scratch directories are deliberately absent: by repository
 * convention they may hold results someone means to keep.
 */
import { existsSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

/** Outputs of a test, benchmark or release run. Deleting one loses nothing a rerun cannot produce. */
export const RUN_ARTIFACTS: readonly string[] = [
  'test-results',
  '.vitest-attachments',
  'coverage',
  '.release',
  'test/perf/results',
  'test/rendering/browser/__screenshots__',
  'test/rendering/parity/__screenshots__',
  'site/.api-staging',
  'site/dist',
];

/** Caches and synced inputs a build recreates; deleting one only costs the next build its warm start. */
export const BUILD_CACHES: readonly string[] = ['.cache', 'site/.astro', 'site/public/vendor', 'site/public/assets', 'site/public/examples'];

const directorySize = (dir: string): number => {
  let total = 0;

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);

    if (entry.isDirectory()) total += directorySize(full);
    else if (entry.isFile()) total += statSync(full).size;
  }

  return total;
};

export interface ArtifactPresence {
  readonly path: string;
  readonly bytes: number;
}

/** The listed paths that currently exist under `root`, with their size on disk. */
export const presentArtifacts = (root: string, paths: readonly string[]): ArtifactPresence[] =>
  paths.filter(path => existsSync(join(root, path))).map(path => ({ path, bytes: directorySize(join(root, path)) }));

export const formatBytes = (bytes: number): string => (bytes >= 1024 * 1024 ? `${(bytes / (1024 * 1024)).toFixed(0)} MB` : `${(bytes / 1024).toFixed(0)} KB`);
