/**
 * Deterministic generator for `examples/shared/assets-global.d.ts`.
 *
 * The playground/Monaco editor injects a typed `assets` global into every
 * example runtime (no import). For hierarchical autocomplete and exact literal
 * types to work in Monaco — which loads `.d.ts` extra-libs into an isolated
 * virtual filesystem and cannot follow a relative `import type` into the
 * canonical catalog module — the global declaration must be SELF-CONTAINED:
 * the full nested object type is inlined as string/number literals.
 *
 * Source of truth: `examples/assets/assets.ts` (the canonical hierarchical
 * catalog). This module renders that object into a `.d.ts` so there is exactly
 * one place the structure is authored. `examples:sync` regenerates the file;
 * `test/examples/assets-global-dts.test.ts` fails the build on any drift.
 *
 * Run directly to (re)write the file: `tsx scripts/generate-examples-global-dts.ts`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const INDENT = '    ';

const isSafeIdentifier = (key: string): boolean => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);

const renderKey = (key: string): string => (isSafeIdentifier(key) ? key : JSON.stringify(key));

/**
 * Renders a JS value into a TypeScript type literal with exact literals:
 *   - string → the single-quoted string literal
 *   - number → the numeric literal
 *   - object → `{ readonly key: <type>; … }` (deterministic key order = source order)
 */
const renderType = (value: unknown, depth: number): string => {
  if (typeof value === 'string') {
    // Single quotes to match the engine's Prettier/style; the catalog values
    // are plain paths with no quotes to escape.
    return `'${value.replace(/'/g, "\\'")}'`;
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (value && typeof value === 'object') {
    const innerPad = INDENT.repeat(depth + 1);
    const closePad = INDENT.repeat(depth);
    const lines = Object.entries(value as Record<string, unknown>).map(
      ([key, child]) => `${innerPad}readonly ${renderKey(key)}: ${renderType(child, depth + 1)};`,
    );
    return `{\n${lines.join('\n')}\n${closePad}}`;
  }
  // The catalog only contains strings, numbers, and nested objects.
  return 'never';
};

/**
 * Renders the full self-contained `assets-global.d.ts` content for a catalog
 * object. Deterministic: identical input always yields byte-identical output
 * (LF newlines, trailing newline).
 */
export const renderAssetsGlobalDts = (assets: Record<string, unknown>): string => {
  const catalogType = renderType(assets, 0);

  return `${[
    '// AUTO-GENERATED by \`pnpm -C site examples:sync\` — DO NOT EDIT BY HAND.',
    '// Source of truth: examples/assets/assets.ts (the canonical hierarchical catalog).',
    '// Regenerate with \`tsx scripts/generate-examples-global-dts.ts\`; drift is guarded',
    '// by test/examples/assets-global-dts.test.ts.',
    '//',
    '// Self-contained, importless typing for the globally-injected `assets` catalog.',
    '// The value is installed on `globalThis`/`window` by the controlled example',
    '// runtimes (Playground iframe, Example/Guide preview, Asset Browser, smoke',
    '// harness, Full Release harness) BEFORE the example module evaluates. Example',
    '// authors use it directly with full autocomplete and exact literal types — no',
    '// import:',
    '//',
    '//   assets.demo.textures.particleFlame;',
    '//   assets.demo.audio.musicLoop;',
    '//   assets.technical.alpha.alphaEdgeStraight;',
    '//',
    '// It is NOT part of the engine public API and is unavailable in consumer apps.',
    '',
    `type ExampleAssetCatalog = ${catalogType};`,
    '',
    'declare global {',
    '    const assets: ExampleAssetCatalog;',
    '',
    '    interface Window {',
    '        readonly assets: ExampleAssetCatalog;',
    '    }',
    '}',
    '',
    'export {};',
  ].join('\n')}\n`;
};

/** Repository-root-relative path of the generated declaration. */
export const ASSETS_GLOBAL_DTS_RELATIVE = 'examples/shared/assets-global.d.ts';

// Resolved lazily so importing this module under Vite/Vitest (where
// `import.meta.url` may be a non-file URL) never throws at module-eval time.
const assetsGlobalDtsPath = (): string => resolve(dirname(fileURLToPath(import.meta.url)), '..', ASSETS_GLOBAL_DTS_RELATIVE);

/**
 * Renders the declaration for the canonical catalog and writes it to disk only
 * when the content changed (keeps mtimes stable for incremental tooling).
 * Returns `true` when the file was rewritten.
 */
export const writeAssetsGlobalDts = async (): Promise<boolean> => {
  // Import the canonical catalog lazily so the pure renderer above stays
  // dependency-free and trivially unit-testable.
  const { assets } = (await import('../examples/assets/assets.ts')) as { assets: Record<string, unknown> };
  const next = renderAssetsGlobalDts(assets);
  const target = assetsGlobalDtsPath();

  let current = '';
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    current = '';
  }

  if (current === next) {
    return false;
  }

  writeFileSync(target, next, 'utf8');
  return true;
};

// Allow `tsx scripts/generate-examples-global-dts.ts` to regenerate in place.
if (import.meta.url.startsWith('file:') && fileURLToPath(import.meta.url) === resolve(process.argv[1] ?? '')) {
  writeAssetsGlobalDts()
    .then(changed => {
      process.stdout.write(
        changed
          ? `[generate-examples-global-dts] Wrote ${ASSETS_GLOBAL_DTS_RELATIVE}\n`
          : `[generate-examples-global-dts] ${ASSETS_GLOBAL_DTS_RELATIVE} already up to date\n`,
      );
    })
    .catch((error: unknown) => {
      process.stderr.write(`[generate-examples-global-dts] ${error instanceof Error ? error.message : String(error)}\n`);
      process.exit(1);
    });
}
