import { ChannelOffset } from 'types/input';

export enum GamepadChannel {
    ButtonSouth = ChannelOffset.gamepads + 0,
    ButtonWest = ChannelOffset.gamepads + 1,
    ButtonEast = ChannelOffset.gamepads + 2,
    ButtonNorth = ChannelOffset.gamepads + 3,
    LeftShoulder = ChannelOffset.gamepads + 4,
    RightShoulder = ChannelOffset.gamepads + 5,
    LeftTrigger = ChannelOffset.gamepads + 6,
    RightTrigger = ChannelOffset.gamepads + 7,
    Select = ChannelOffset.gamepads + 8,
    Start = ChannelOffset.gamepads + 9,
    LeftStick = ChannelOffset.gamepads + 10,
    RightStick = ChannelOffset.gamepads + 11,
    DPadUp = ChannelOffset.gamepads + 12,
    DPadDown = ChannelOffset.gamepads + 13,
    DPadLeft = ChannelOffset.gamepads + 14,
    DPadRight = ChannelOffset.gamepads + 15,
    Guide = ChannelOffset.gamepads + 16,
    Share = ChannelOffset.gamepads + 17,
    Capture = ChannelOffset.gamepads + 18,
    Touchpad = ChannelOffset.gamepads + 19,
    Paddle1 = ChannelOffset.gamepads + 20,
    LeftStickLeft = ChannelOffset.gamepads + 21,
    LeftStickRight = ChannelOffset.gamepads + 22,
    LeftStickUp = ChannelOffset.gamepads + 23,
    LeftStickDown = ChannelOffset.gamepads + 24,
    RightStickLeft = ChannelOffset.gamepads + 25,
    RightStickRight = ChannelOffset.gamepads + 26,
    RightStickUp = ChannelOffset.gamepads + 27,
    RightStickDown = ChannelOffset.gamepads + 28,
    AuxiliaryAxis0Negative = ChannelOffset.gamepads + 29,
    AuxiliaryAxis0Positive = ChannelOffset.gamepads + 30,
    AuxiliaryAxis1Negative = ChannelOffset.gamepads + 31,
    AuxiliaryAxis1Positive = ChannelOffset.gamepads + 32,
    AuxiliaryAxis2Negative = ChannelOffset.gamepads + 33,
    AuxiliaryAxis2Positive = ChannelOffset.gamepads + 34,
    AuxiliaryAxis3Negative = ChannelOffset.gamepads + 35,
    AuxiliaryAxis3Positive = ChannelOffset.gamepads + 36,
}
