import { ChannelOffset } from 'types/input';

export class GamepadChannels {
    public static readonly faceBottom = ChannelOffset.gamepads + 0;
    public static readonly faceLeft = ChannelOffset.gamepads + 1;
    public static readonly faceRight = ChannelOffset.gamepads + 2;
    public static readonly faceTop = ChannelOffset.gamepads + 3;
    public static readonly shoulderLeftBottom = ChannelOffset.gamepads + 4;
    public static readonly shoulderRightBottom = ChannelOffset.gamepads + 5;
    public static readonly shoulderLeftTop = ChannelOffset.gamepads + 6;
    public static readonly shoulderRightTop = ChannelOffset.gamepads + 7;
    public static readonly menuLeft = ChannelOffset.gamepads + 8;
    public static readonly menuRight = ChannelOffset.gamepads + 9;
    public static readonly leftStickPress = ChannelOffset.gamepads + 10;
    public static readonly rightStickPress = ChannelOffset.gamepads + 11;
    public static readonly dPadUp = ChannelOffset.gamepads + 12;
    public static readonly dPadDown = ChannelOffset.gamepads + 13;
    public static readonly dPadLeft = ChannelOffset.gamepads + 14;
    public static readonly dPadRight = ChannelOffset.gamepads + 15;
    public static readonly menuCenter = ChannelOffset.gamepads + 16;
    public static readonly menuSpecial = ChannelOffset.gamepads + 17;
    public static readonly extra1 = ChannelOffset.gamepads + 18;
    public static readonly extra2 = ChannelOffset.gamepads + 19;
    public static readonly extra3 = ChannelOffset.gamepads + 20;
    public static readonly leftStickLeft = ChannelOffset.gamepads + 21;
    public static readonly leftStickRight = ChannelOffset.gamepads + 22;
    public static readonly leftStickUp = ChannelOffset.gamepads + 23;
    public static readonly leftStickDown = ChannelOffset.gamepads + 24;
    public static readonly rightStickLeft = ChannelOffset.gamepads + 25;
    public static readonly rightStickRight = ChannelOffset.gamepads + 26;
    public static readonly rightStickUp = ChannelOffset.gamepads + 27;
    public static readonly rightStickDown = ChannelOffset.gamepads + 28;
    public static readonly auxiliaryAxis0Negative = ChannelOffset.gamepads + 29;
    public static readonly auxiliaryAxis0Positive = ChannelOffset.gamepads + 30;
    public static readonly auxiliaryAxis1Negative = ChannelOffset.gamepads + 31;
    public static readonly auxiliaryAxis1Positive = ChannelOffset.gamepads + 32;
    public static readonly auxiliaryAxis2Negative = ChannelOffset.gamepads + 33;
    public static readonly auxiliaryAxis2Positive = ChannelOffset.gamepads + 34;
    public static readonly auxiliaryAxis3Negative = ChannelOffset.gamepads + 35;
    public static readonly auxiliaryAxis3Positive = ChannelOffset.gamepads + 36;
    public static readonly select = GamepadChannels.menuLeft;
    public static readonly start = GamepadChannels.menuRight;
    public static readonly leftStick = GamepadChannels.leftStickPress;
    public static readonly rightStick = GamepadChannels.rightStickPress;
    public static readonly home = GamepadChannels.menuCenter;
}
