import { ChannelOffset } from 'input/types';

export enum GamepadChannel {
    ButtonSouth = ChannelOffset.Gamepads + 0,
    ButtonWest = ChannelOffset.Gamepads + 1,
    ButtonEast = ChannelOffset.Gamepads + 2,
    ButtonNorth = ChannelOffset.Gamepads + 3,
    LeftShoulder = ChannelOffset.Gamepads + 4,
    RightShoulder = ChannelOffset.Gamepads + 5,
    LeftTrigger = ChannelOffset.Gamepads + 6,
    RightTrigger = ChannelOffset.Gamepads + 7,
    Select = ChannelOffset.Gamepads + 8,
    Start = ChannelOffset.Gamepads + 9,
    LeftStick = ChannelOffset.Gamepads + 10,
    RightStick = ChannelOffset.Gamepads + 11,
    DPadUp = ChannelOffset.Gamepads + 12,
    DPadDown = ChannelOffset.Gamepads + 13,
    DPadLeft = ChannelOffset.Gamepads + 14,
    DPadRight = ChannelOffset.Gamepads + 15,
    Guide = ChannelOffset.Gamepads + 16,
    Share = ChannelOffset.Gamepads + 17,
    Capture = ChannelOffset.Gamepads + 18,
    Touchpad = ChannelOffset.Gamepads + 19,
    Paddle1 = ChannelOffset.Gamepads + 20,
    LeftStickLeft = ChannelOffset.Gamepads + 21,
    LeftStickRight = ChannelOffset.Gamepads + 22,
    LeftStickUp = ChannelOffset.Gamepads + 23,
    LeftStickDown = ChannelOffset.Gamepads + 24,
    RightStickLeft = ChannelOffset.Gamepads + 25,
    RightStickRight = ChannelOffset.Gamepads + 26,
    RightStickUp = ChannelOffset.Gamepads + 27,
    RightStickDown = ChannelOffset.Gamepads + 28,
    AuxiliaryAxis0Negative = ChannelOffset.Gamepads + 29,
    AuxiliaryAxis0Positive = ChannelOffset.Gamepads + 30,
    AuxiliaryAxis1Negative = ChannelOffset.Gamepads + 31,
    AuxiliaryAxis1Positive = ChannelOffset.Gamepads + 32,
    AuxiliaryAxis2Negative = ChannelOffset.Gamepads + 33,
    AuxiliaryAxis2Positive = ChannelOffset.Gamepads + 34,
    AuxiliaryAxis3Negative = ChannelOffset.Gamepads + 35,
    AuxiliaryAxis3Positive = ChannelOffset.Gamepads + 36,
}
