
export enum ChannelSize {
    Container = 3 << 8,
    Category = 1 << 8,
    Gamepad = 1 << 6,
}

export const enum ChannelOffset {
    Keyboard = 0 * ChannelSize.Category,
    Pointers = 1 * ChannelSize.Category,
    Gamepads = 2 * ChannelSize.Category,
}

/** Maximum number of simultaneous tracked pointers (mouse / touch / pen). */
export const maxPointers = 16;

/** Number of channel slots reserved per pointer. 16 pointers × 16 slots = 256 (fills the Pointers category exactly). */
export const pointerSlotSize = 16;

/**
 * Channel offsets for unified pointer (mouse / touch / pen) state.
 *
 * The un-prefixed aliases (Active, X, Y, …) are identical to Slot0Active, Slot0X, Slot0Y, …
 * and address the primary pointer (slot 0). Use Slot{N}Active / Slot{N}X / Slot{N}Y for
 * multi-pointer (e.g. pinch) access. Other per-slot channels beyond Active/X/Y are reachable
 * via arithmetic: `Pointer.X + slotIndex * pointerSlotSize + channelOffset` (Pointer.X = PointerChannel.X).
 *
 * @internal — accessed publicly via the `Pointer` class namespace (see Pointer.ts).
 */
export enum PointerChannel {
    // --- Convenience aliases for the primary pointer (slot 0) ---
    Active    = ChannelOffset.Pointers + 0,
    X         = ChannelOffset.Pointers + 1,
    Y         = ChannelOffset.Pointers + 2,
    Pressure  = ChannelOffset.Pointers + 3,
    Width     = ChannelOffset.Pointers + 4,
    Height    = ChannelOffset.Pointers + 5,
    Twist     = ChannelOffset.Pointers + 6,
    TiltX     = ChannelOffset.Pointers + 7,
    TiltY     = ChannelOffset.Pointers + 8,
    Left      = ChannelOffset.Pointers + 9,
    Right     = ChannelOffset.Pointers + 10,
    Middle    = ChannelOffset.Pointers + 11,
    IsMouse   = ChannelOffset.Pointers + 12,
    IsTouch   = ChannelOffset.Pointers + 13,
    IsPen     = ChannelOffset.Pointers + 14,
    IsPrimary = ChannelOffset.Pointers + 15,

    // --- Per-slot Active/X/Y for multi-pointer access ---
    Slot0Active  = ChannelOffset.Pointers + 0 * 16 + 0,
    Slot0X       = ChannelOffset.Pointers + 0 * 16 + 1,
    Slot0Y       = ChannelOffset.Pointers + 0 * 16 + 2,
    Slot1Active  = ChannelOffset.Pointers + 1 * 16 + 0,
    Slot1X       = ChannelOffset.Pointers + 1 * 16 + 1,
    Slot1Y       = ChannelOffset.Pointers + 1 * 16 + 2,
    Slot2Active  = ChannelOffset.Pointers + 2 * 16 + 0,
    Slot2X       = ChannelOffset.Pointers + 2 * 16 + 1,
    Slot2Y       = ChannelOffset.Pointers + 2 * 16 + 2,
    Slot3Active  = ChannelOffset.Pointers + 3 * 16 + 0,
    Slot3X       = ChannelOffset.Pointers + 3 * 16 + 1,
    Slot3Y       = ChannelOffset.Pointers + 3 * 16 + 2,
    Slot4Active  = ChannelOffset.Pointers + 4 * 16 + 0,
    Slot4X       = ChannelOffset.Pointers + 4 * 16 + 1,
    Slot4Y       = ChannelOffset.Pointers + 4 * 16 + 2,
    Slot5Active  = ChannelOffset.Pointers + 5 * 16 + 0,
    Slot5X       = ChannelOffset.Pointers + 5 * 16 + 1,
    Slot5Y       = ChannelOffset.Pointers + 5 * 16 + 2,
    Slot6Active  = ChannelOffset.Pointers + 6 * 16 + 0,
    Slot6X       = ChannelOffset.Pointers + 6 * 16 + 1,
    Slot6Y       = ChannelOffset.Pointers + 6 * 16 + 2,
    Slot7Active  = ChannelOffset.Pointers + 7 * 16 + 0,
    Slot7X       = ChannelOffset.Pointers + 7 * 16 + 1,
    Slot7Y       = ChannelOffset.Pointers + 7 * 16 + 2,
    Slot8Active  = ChannelOffset.Pointers + 8 * 16 + 0,
    Slot8X       = ChannelOffset.Pointers + 8 * 16 + 1,
    Slot8Y       = ChannelOffset.Pointers + 8 * 16 + 2,
    Slot9Active  = ChannelOffset.Pointers + 9 * 16 + 0,
    Slot9X       = ChannelOffset.Pointers + 9 * 16 + 1,
    Slot9Y       = ChannelOffset.Pointers + 9 * 16 + 2,
    Slot10Active = ChannelOffset.Pointers + 10 * 16 + 0,
    Slot10X      = ChannelOffset.Pointers + 10 * 16 + 1,
    Slot10Y      = ChannelOffset.Pointers + 10 * 16 + 2,
    Slot11Active = ChannelOffset.Pointers + 11 * 16 + 0,
    Slot11X      = ChannelOffset.Pointers + 11 * 16 + 1,
    Slot11Y      = ChannelOffset.Pointers + 11 * 16 + 2,
    Slot12Active = ChannelOffset.Pointers + 12 * 16 + 0,
    Slot12X      = ChannelOffset.Pointers + 12 * 16 + 1,
    Slot12Y      = ChannelOffset.Pointers + 12 * 16 + 2,
    Slot13Active = ChannelOffset.Pointers + 13 * 16 + 0,
    Slot13X      = ChannelOffset.Pointers + 13 * 16 + 1,
    Slot13Y      = ChannelOffset.Pointers + 13 * 16 + 2,
    Slot14Active = ChannelOffset.Pointers + 14 * 16 + 0,
    Slot14X      = ChannelOffset.Pointers + 14 * 16 + 1,
    Slot14Y      = ChannelOffset.Pointers + 14 * 16 + 2,
    Slot15Active = ChannelOffset.Pointers + 15 * 16 + 0,
    Slot15X      = ChannelOffset.Pointers + 15 * 16 + 1,
    Slot15Y      = ChannelOffset.Pointers + 15 * 16 + 2,
}

export enum Keyboard {
    Backspace = ChannelOffset.Keyboard + 8,
    Tab = ChannelOffset.Keyboard + 9,
    Clear = ChannelOffset.Keyboard + 12,
    Enter = ChannelOffset.Keyboard + 13,
    Shift = ChannelOffset.Keyboard + 16,
    Control = ChannelOffset.Keyboard + 17,
    Alt = ChannelOffset.Keyboard + 18,
    Pause = ChannelOffset.Keyboard + 19,
    CapsLock = ChannelOffset.Keyboard + 20,
    Escape = ChannelOffset.Keyboard + 27,
    Space = ChannelOffset.Keyboard + 32,
    PageUp = ChannelOffset.Keyboard + 33,
    PageDown = ChannelOffset.Keyboard + 34,
    End = ChannelOffset.Keyboard + 35,
    Home = ChannelOffset.Keyboard + 36,
    Left = ChannelOffset.Keyboard + 37,
    Up = ChannelOffset.Keyboard + 38,
    Right = ChannelOffset.Keyboard + 39,
    Down = ChannelOffset.Keyboard + 40,
    Insert = ChannelOffset.Keyboard + 45,
    Delete = ChannelOffset.Keyboard + 46,
    Help = ChannelOffset.Keyboard + 47,
    Zero = ChannelOffset.Keyboard + 48,
    One = ChannelOffset.Keyboard + 49,
    Two = ChannelOffset.Keyboard + 50,
    Three = ChannelOffset.Keyboard + 51,
    Four = ChannelOffset.Keyboard + 52,
    Five = ChannelOffset.Keyboard + 53,
    Six = ChannelOffset.Keyboard + 54,
    Seven = ChannelOffset.Keyboard + 55,
    Eight = ChannelOffset.Keyboard + 56,
    Nine = ChannelOffset.Keyboard + 57,
    A = ChannelOffset.Keyboard + 65,
    B = ChannelOffset.Keyboard + 66,
    C = ChannelOffset.Keyboard + 67,
    D = ChannelOffset.Keyboard + 68,
    E = ChannelOffset.Keyboard + 69,
    F = ChannelOffset.Keyboard + 70,
    G = ChannelOffset.Keyboard + 71,
    H = ChannelOffset.Keyboard + 72,
    I = ChannelOffset.Keyboard + 73,
    J = ChannelOffset.Keyboard + 74,
    K = ChannelOffset.Keyboard + 75,
    L = ChannelOffset.Keyboard + 76,
    M = ChannelOffset.Keyboard + 77,
    N = ChannelOffset.Keyboard + 78,
    O = ChannelOffset.Keyboard + 79,
    P = ChannelOffset.Keyboard + 80,
    Q = ChannelOffset.Keyboard + 81,
    R = ChannelOffset.Keyboard + 82,
    S = ChannelOffset.Keyboard + 83,
    T = ChannelOffset.Keyboard + 84,
    U = ChannelOffset.Keyboard + 85,
    V = ChannelOffset.Keyboard + 86,
    W = ChannelOffset.Keyboard + 87,
    X = ChannelOffset.Keyboard + 88,
    Y = ChannelOffset.Keyboard + 89,
    Z = ChannelOffset.Keyboard + 90,
    NumPad0 = ChannelOffset.Keyboard + 96,
    NumPad1 = ChannelOffset.Keyboard + 97,
    NumPad2 = ChannelOffset.Keyboard + 98,
    NumPad3 = ChannelOffset.Keyboard + 99,
    NumPad4 = ChannelOffset.Keyboard + 100,
    NumPad5 = ChannelOffset.Keyboard + 101,
    NumPad6 = ChannelOffset.Keyboard + 102,
    NumPad7 = ChannelOffset.Keyboard + 103,
    NumPad8 = ChannelOffset.Keyboard + 104,
    NumPad9 = ChannelOffset.Keyboard + 105,
    NumPadMultiply = ChannelOffset.Keyboard + 106,
    NumPadAdd = ChannelOffset.Keyboard + 107,
    NumPadEnter = ChannelOffset.Keyboard + 108,
    NumPadSubtract = ChannelOffset.Keyboard + 109,
    NumPadDecimal = ChannelOffset.Keyboard + 110,
    NumPadDivide = ChannelOffset.Keyboard + 111,
    F1 = ChannelOffset.Keyboard + 112,
    F2 = ChannelOffset.Keyboard + 113,
    F3 = ChannelOffset.Keyboard + 114,
    F4 = ChannelOffset.Keyboard + 115,
    F5 = ChannelOffset.Keyboard + 116,
    F6 = ChannelOffset.Keyboard + 117,
    F7 = ChannelOffset.Keyboard + 118,
    F8 = ChannelOffset.Keyboard + 119,
    F9 = ChannelOffset.Keyboard + 120,
    F10 = ChannelOffset.Keyboard + 121,
    F11 = ChannelOffset.Keyboard + 122,
    F12 = ChannelOffset.Keyboard + 123,
    NumLock = ChannelOffset.Keyboard + 144,
    ScrollLock = ChannelOffset.Keyboard + 145,
    Colon = ChannelOffset.Keyboard + 186,
    Equals = ChannelOffset.Keyboard + 187,
    Comma = ChannelOffset.Keyboard + 188,
    Dash = ChannelOffset.Keyboard + 189,
    Period = ChannelOffset.Keyboard + 190,
    QuestionMark = ChannelOffset.Keyboard + 191,
    Tilde = ChannelOffset.Keyboard + 192,
    OpenBracket = ChannelOffset.Keyboard + 219,
    BackwardSlash = ChannelOffset.Keyboard + 220,
    ClosedBracket = ChannelOffset.Keyboard + 221,
    Quotes = ChannelOffset.Keyboard + 222,
}
